/*==== INSERT ====*/

INSERT INTO faculty (id, name, image_url) VALUES
('architecture', 'Architecture', 'faculty-architecture.webp'),
('automatic-control-robotics-electrical-engineering', 'Automatic Control, Robotics & Electrical Engineering', 'faculty-automatic-control-robotics-electrical-engineering.webp'),
('chemical-technology', 'Chemical Technology', 'faculty-chemical-technology.webp'),
('civil-transport-engineering', 'Civil and Transport Engineering', 'faculty-civil-transport-engineering.webp'),
('computing-telecommunications', 'Computing and Telecommunications', 'faculty-computing-telecommunications.webp'),
('engineering-management', 'Engineering Management', 'faculty-engineering-management.webp'),
('environmental-engineering-energy', 'Environmental Engineering and Energy', 'faculty-environmental-engineering-energy.webp'),
('materials-engineering-technical-physics', 'Materials Engineering and Technical Physics', 'faculty-materials-engineering-technical-physics.webp'),
('mechanical-engineering', 'Mechanical Engineering', 'faculty-mechanical-engineering.webp');

INSERT INTO course (id, title, description, ects, hours, semester, description_card_url, diploma, faculty_id) VALUES
('object-programming','Object Programming','The goal of the course is to teach students how to model and create reusable, easily-maintainable software, by using tools provided by object-oriented programming languages. Moreover, the students will learn how to create and use custom data types, how to model software systems based on clean code principles, and how to communicate their work to other programmers.',4,60,'Winter','Object-programming.pdf','Bsc','computing-telecommunications'),
('quality-management-experimental-software-engineering','Quality Management and Experimental Software Engineering','Provide students the knowledge regarding experimental Software Engineering, especially related to empirical research methods and their theoretical foundations.',5,125,'Winter','Quality-management-and-experimental-software-engineering.pdf','Master','computing-telecommunications'),
('software-architecture-and-verification','Software Architecture and Verification','Provide students with knowledge regarding software architecture, within the following scope of understanding what is software architecture, how it should be documented and evaluated.',6,145,'Winter','Software-architecture-and-verification.pdf','Master','computing-telecommunications'),
('software-development-studio-2','Software Development Studio 2','Provide to the students the foundations of project management and requirements engineering (and illustrate them with real-life cases) that are necessary to perform the management and analytical roles in software development projects.',6,150,'Winter','Software-development-studio-2.pdf','Master','computing-telecommunications'),
('operational-research','Operational Research','The course aims to introduce the students to the main topics in Operational Research (OR). These include linear programming, simplex algorithm, dual programming, sensitivity analysis, network optimization models, dynamic programming, integer programming, nonlinear programming, job scheduling, and heuristics. The students should get to know the basic methods, techniques, and algorithms for each of these sub-fields to use them for practical problem-solving.',5,60,'Winter','Operational-research.pdf','Bsc','computing-telecommunications'),
('internet-applications','Internet Applications','Gaining knowledge about www document and application development necessary to distinguish between basic internet application architectures and methods for implementing their modules. Enhancing knowledge about network architectures, protocols, and distributed systems security. Gaining skills in web application development using advanced user interface development technologies, such as CSS, JavaScript, presentation logic development, Single Page Application Frameworks, business logic development. Gaining social competences concerning working as a part of a team, including organising team work, in particular leadership and communication in the process of group problem solving.',5,60,'Winter','Internet-applications.pdf','Bsc','computing-telecommunications'),
('information-theory','Information Theory','The objective of the course is to present a selection of aspects of the Information Theory, one of the most fundamental theories underlying theoretical Computer Science of modern­day. The Information Theory deals with representing, storing and communicating information expressed in the form of symbols. Owing to the fact that many important applications of this theory reach far beyond the core of Computing Science, the presented selection of aspects will be confined to the most fundamental ones, mainly those related to such domains of the Computer Science as Data Exploration and Data Compression, in particular: Lossless Data Compression. The fruits of rapid development of notions in the Information Theory, initially disputable and professedly unsolvable, have soon turned out to be incredibly useful and to have a great deal of practical value. In the modern­day these solutions show up in virtually all imaginable computer systems in existence, ones that could hardly survive nowadays without the ubiquitous multimedia content, the popularity and versatility of which has been consistently and unwaveringly influenced by the accessibility of data compression methods.',3,30,'Winter','Internet-applications.pdf','Bsc','computing-telecommunications'),
('career-resources','Career Resources','Provide students with basic knowledge regarding interpersonal communication in the workplace. Provide students with contemporary problems of interpersonal communication. Develop students'' skills in solving problems and communicating in groups. Advancing students'' language competence towards the level at least B2 (CEFR).',2,30,'Winter','Career-resources.pdf','Bsc','computing-telecommunications');

('Occupational-health-and-safety','Occupational Health and Safety','To familiarize students with rules, ordinances and regulations about health and safety at work. To acquaint students with the Basic issues of the methodology of human-oriented design as an operator and as an employee of machine service and other technical devices.',1,20,'Winter','Occupational-health-and-safety.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Physics','Physics','Hand over basic knowledge concerning physics with special emphasis on applications in technical sciences. Develop students abilities to solve physical problems, to perceive potential applications in studied subject, doing experiments and analyze results based on acquired knowledge. Mould students abilities within group cooperation.',4,60,'Winter','Physics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Geometry-and-engineering-graphics', 'Geometry and engineering graphics','Mastership of basic principles of image construction of spatial objects on the plane. Training of spatial imagination. Learning the methods and principles of engineering drawing. Practical skills of preparing the technical documentation. Skills of "reading" the engineering drawing.',3,47,'Winter','Geometry-and-engineering-graphics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Information-Engineering', 'Information Engineering','Learning of basic knowledge concerning computer science as well as construction and operating principles of microcomputers; learning how to devise simple algorithms; learning the basics of structural and object programming in the C++ programming language.',2,35,'Winter','Information-Engineering.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Materials-engineering', 'Materials Engineering','Knowledge of basic materials used in electrical engineering, phenomena occurring in them and characterized them properties. Learning new techniques and research methods.',1,16,'Winter','Information-Engineering.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Mathematics', 'Mathematics','Equipping the student with skills related to the use of concepts and methods of mathematical analysis,linear algebra and vector calculus to describe and analyze problems in the field of technical sciences.',9,124,'Winter','Mathematics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Circuits-theory', 'Circuits theory','Introduction to physical quantities and basic laws and theorems in the field of direct current electric circuits and sinusoidal alternating. Knowledge of analytical methods for calculating electrical circuits steady state.',6,75,'Winter','Circuits-theory.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Physical-education', 'Physical education','Didactic: learning the technique and tactics of the game that can be used in everyday life during the professional period, learning how to organize a match, competition, betting tournament with correct scoring and table execution, refereeing. Educational: respect for the rival, partner, the ability to support, mobilize and encourage a partner who is not successful in the game, cooperation and respect for the referee, care and respect for sports and personal equipment, care for personal hygiene. Health: Organization of leisure time, spending free time effectively, taking care of one's efficiency and fitness, instilling correct hygiene habits, implementing correct standards of taking care of one's appearance and proper efficiency, which positively affects the efficiency of work.',0,30,'Winter','Physical-education.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Physics','Physics','Hand over basic knowledge concerning physics with special emphasis on applications in technical sciences. Develop students abilities to solve physical problems, to perceive potential applications in studied subject, doing experiments and analyze results based on acquired knowledge. Mould students abilities within group cooperation.',4,62,'Summer','Physics-Summer.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Information-technology', 'Understanding theoretical and practical issues related to the use of selected elements and information systems. Acquiring the ability to develop projects in the area of databases (relational model). Introduction to the theoretical and practical aspects of the basics of visual programming in the .NET environment (C # language in engineering issues).',4,50,'Summer','Information-technology.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Materials-engineering-Summer', 'Materials Engineering','Knowledge of basic materials used in electrical engineering, phenomena occurring in them and characterized them properties. Learning new techniques and research methods.',1,18,'Summer','Materials-Engineering-Summer.pdf','Bsc','control-robotics-and-electrical-engineering'),
('English', 'English','To help the student achieve the ability to use general and field-specific language effectively, with respect to the following language skills: listening, reading, writing, speaking. To improve the student's ability to function effectively on the international job market and in everyday life. ',2,35,'Summer','English.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electrical-machines', 'Electrical machines','Learning of construction, principles of operation, characteristics, exploitation properties and basic methods of analysis of typical operation states of transformers and induction machines. Learning of basic methods of calculation of magnetic circuits in electromagnetic converters.',2,35,'Summer','Electrical-machines.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Mathematics-Summer', 'Mathematics','Equipping the student with skills related to the use of concepts and methods of mathematical analysis,linear algebra and vector calculus to describe and analyze problems in the field of technical sciences.',6,87,'Summer','Mathematics-Summer.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Numerical-methods', 'Numerical methods','Learning of numerical methods and apply them to solve simple engineering problems in mathematics and the field of electrical engineering. The support of engineering calculations by relevant IT tools',3,34,'Summer','Numerical-methods.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Metrology', 'Metrology','Knowledge of measurementmethodology, attributes of modern measuring devices and equipment, principles of using analog and digitalmeasuring devices, and evaluation of measurementresults.',2,30,'Summer','Metrology.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Circuits-theory-Summer', 'Circuits theory','Introduction to physical quantities and basic laws and theorems in the field of direct current electric circuits and sinusoidal alternating. Knowledge of analytical methods for calculating electrical circuits steady state.',8,120,'Summer','Circuits-theory-summer.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Physical-education-Summer', 'Physical education','Didactic: learning the technique and tactics of the game that can be used in everyday life during the professional period, learning how to organize a match, competition, betting tournament with correct scoring and table execution, refereeing. Educational: respect for the rival, partner, the ability to support, mobilize and encourage a partner who is not successful in the game, cooperation and respect for the referee, care and respect for sports and personal equipment, care for personal hygiene. Health: Organization of leisure time, spending free time effectively, taking care of one's efficiency and fitness, instilling correct hygiene habits, implementing correct standards of taking care of one's appearance and proper efficiency, which positively affects the efficiency of work.',0,30,'Summer','Physical-education-Summer.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Automation-and-automatic-regulation', 'Automation and automatic regulation','To provide students with the knowledge of the basic elements of auto systems, principles of the selection of controllers and their parameters in various control systems. To familiarise students with the methods of synthesis and analysis of the continuous-time control systems operation, using various methods of analysis and digital modelling',4,65,'Winter','Automation-and-automatic-regulation.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electronics-and-power-electronics', 'Electronics and power electronics','Familiarization with the construction, parameters and applications of basic electronic components. Getting to know the principles of operation of analog and digital electronic circuits. Acquiring the ability to design electronic circuits at the basic level.',3,50,'Winter','Electronics-and-power-electronics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Information-technology-winter2', 'Information technology','Acquiring practical skills in creating a database in an MS Access environment. Learning visual-object programming in the .NET environment (MS Visual C#)',1,17,'Winter','Information-technology-winter2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('English-winter2', 'English','To help the student achieve the ability to use general and field-specific language effectively, with respect to the following language skills: listening, reading, writing, speaking. To improve the student's ability to function effectively on the international job market and in everyday life. ',2,35,'Winter','English-winter2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electrical-machines-winter2', 'Electrical machines','Learning of construction, principles of operation, characteristics, exploitation properties and basic methods of analysis of typical operation states of transformers and induction machines. Learning of basic methods of calculation of magnetic circuits in electromagnetic converters.',2,35,'Winter','Electrical-machines-winter2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Mechanics-and-mechatronics', 'Mechanics and mechatronics','Cognizing and understanding the main concepts and laws of mechanics. Developing skills in modeling mechanical systems being parts of mechatronic systems and in solving problems related to the movement and the equilibrium of mechanical systems',2,38,'Winter','Mechanics-and-mechatronics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Metrology-winter2', 'Metrology','Knowledge of measurementmethodology, attributes of modern measuring devices and equipment, principles of using analog and digitalmeasuring devices, and evaluation of measurementresults.',4,60,'Winter','Metrology-winter2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Basics-of-Lighting-Engineering', 'Mechanics and mechatronics','Providing students with basic information on visible radiation and the functioning of the eye, basic light quantities, basic laws of lighting technology, construction. To familiarize students with the construction, principle of operation and basic characteristics of electric lamps. Discussion of the basic normative requirements in the field of interior lighting, emergency lighting and road lighting.',5,70,'Winter','Basics-of-Lighting-Engineering.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electromagnetic-Field-Theory', 'Electromagnetic Field Theory','Understanding the physical quantities and laws of the electromagnetic field. Understanding the analytical methods used to calculate the parameters of the electromagnetic field.',5,90,'Winter','Electromagnetic-Field-Theory.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electrical-Power-Engineering', 'Electrical Power Engineering','Understanding the structure and characteristic features of the power system and the physical foundations of electricity generation in various types of power plants. Understanding the issues related to fuel combustion.',3,47,'Summer','Electrical-Power-Engineering.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electronics-and-power-electronics-summer2', 'Electronics and power electronics','Understanding the properties and basic power electronic characteristics of semiconductor devices. Getting to know the construction, principle of operation and properties of power electronics converters used. Learning selected power theories',4,70,'Summer','Electronics-and-power-electronics-summer2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('English-summer2', 'English','To advance the student’s language competence towards level B2 (CEFR).To help the student achieve  the ability to use general and field-specific language effectively, with respect to the following language skills: listening, reading, writing, speaking. To perfect the student’s ability to use field-specific texts and to familiarize the student with basic translation techniques. To develop the student's ability to recognize and express cause-effect relationships.To foster the habit of logical thinking (analysis and synthesis of information).',4,67,'Summer','English-summer2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Computerization-of-design-in-electrical-engineering', 'Computerization of design in electrical engineering','Understanding selected numerical methods in application to solve problems in the field of circuit theory and power engineering, learning examples of tools for design in the field of broadly understood electrical engineering.',2,38,'Summer','Computerization-of-design-in-electrical-engineering.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electrical-machines-summer2', 'Electrical machines','Getting to know construction, principles of operation, characteristics, exploitation properties and basic methods of analysis of typical operation states of synchronous, commutator and special machines. Learning the fundamental methods of investigation and measurements of electrical machines',6,105,'Summer','Electrical-machines-summer2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Mechanics-and-mechatronics-summer2', 'Mechanics and mechatronics','The main goal is to obtain knowledge of the basics of mechatronics. Introduction to the design and principle of work of mechatronic devices',1,15,'Summer','Mechanics-and-mechatronics-summer2.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Holiday-(summer)-internship', 'Holiday (summer) internship','Gaining practical knowledge of issues related to the field of study.',4,100,'Summer','Holiday-(summer)-internship.pdf','Bsc','control-robotics-and-electrical-engineering'),
('High-voltage-engineering', 'High voltage engineering','To know simple tasks connected to high voltage engineering. To know sources of test Voltage. To know methods of measurements of typical properties for high voltage engineering. To know fundamental definitions regarding to overvoltage protection. ',3,45,'Summer','High-voltage-engineering.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electrical-Power-Engineering-winter3', 'Electrical Power Engineering','Learning about the construction and principles of operation of gas-fired and gas-steam power plants and combined heat and power plants. The use of renewable sources for the production of electricity. Getting to know issues related to nuclear energy.',2,20,'Winter','Electrical-Power-Engineering-winter3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electronics-and-power-electronics-winter3', 'Electronics and power electronics','Practical knowledge of propriety and basic characteristics of power electronics converters, rectifiers, AC/AC converters, AC/DC converters and inverters.',2,40,'Winter','Electronics-and-power-electronics-winter3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Computerization-of-design-in-electrical-engineering-winter3', 'Computerization of design in electrical engineering','Acquiring the ability to implement in the computer environment (MS Visual Studio C #) selected numerical methods in solving problems in the field of circuit theory and power engineering, learning examples of tools for design in the field of broadly understood electrical engineering',1,20,'Winter','Computerization-of-design-in-electrical-engineering-winter3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Renewable-energy-sources', 'Renewable energy sources','To acquaint students with the structure, principles of operation and application possibilities of renewable energy: photovoltaic, wind energy and water. Reason the need to replace conventional sources for renewable, due to the depletion of the former and growing environmental pollution. Presentation of new opportunities in the field of sourcing electricity',2,46,'Winter','Renewable-energy-sources.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Optoelectronic', 'Optoelectronic','Providing students with basic knowledge in the field of optoelectronics and photonics useful in the design and application process min. in control and measurement, telecommunications, industrial and sensory systems.',1,15,'Winter','Optoelectronic.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Semester-internship', 'Semester internship','Gaining practical knowledge of issues related to the field of study.',6,160,'Winter','Semester-internship.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Transmission-and-distribution-of-electric-power-energy', 'Transmission and distribution of electric power energy','Acquaintance with the parameters and tasks of modern power systems, electricity transmission and distribution subsystems. Construction of AC transmission systems. Transmission of electricity over short and long distances. Control of power transmission in AC transmission systems. Application of current transmission systems.',5,73,'Winter','Transmission-and-distribution-of-electric-power-energy.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Microprocessor-technology', 'Microprocessor technology','Thorough knowledge of theoretical and practical problems associated with the construction elements, components and microprocessor systems and the basis of their programming and design',4,61,'Winter','Microprocessor-technology.pdf','Bsc','control-robotics-and-electrical-engineering'),
('High-voltage-engineering-winter3', 'Knowledge of extended issues related to high voltage engineering. Understanding the values describing the parameters of insulation systems operating at high voltages. Understanding the mechanisms of electrical breakdown in various insulating materials. Understanding the issues related to the construction of high voltage insulation systems for power equipment',2,20,'Winter','High-voltage-engineering-winter3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electrical-devices', 'Electrical devices','Knowledge of phenomena occurring in electrical devices and systems as well as their mathematical and physical descriptions. Purchase of skills in the application of phenomena description to design of power supply and hazard assessment that can occurs in these systems. Experiment planning, selection of measurement instrument, realization of test set-up, researches performing and results analyzing.',2,44,'Winter','Electrical-devices.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Introduction-to-telecommunication', 'Introduction to telecommunication','Providing students with knowledge related to basic signal processing and information transmission techniques (analogue and digital) in wired and wireless telecommunications systems. Acquisition and development of practical skills of measurement and analysis of antenna and transmission line parameters, as well as signal spectral analysis',3,50,'Winter','Introduction-to-telecommunication.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Technical-Electrodynamics', 'Technical Electrodynamics','The student should obtain knowledge of the description and analysis of electromagnetic phenomena in electrical devices as well as knowledge of finite element method in electromagnetism.',3,53,'Summer','Technical-Electrodynamics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Ergonomics-and-safety-use-of-electrical-equipment', 'Ergonomics and safety use of electrical equipment','Understanding the hazards associated with electrical equipment and the principles and measures of protection against these hazards. Able to asses the nature and degree of electric shock and select measures of protection. Knows the general requirements of ergonomics and fulfill them in a limited way',2,44,'Summer','Ergonomics-and-safety-use-of-electrical-equipment.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Optoelectronic-summer3', 'Optoelectronic','Knowledge of fundamentals of optoelectronics and photonics and the selected applications of modern optoelectronic devices and equipment',1,17,'Summer','Optoelectronic-summer3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Holiday-(summer)-internship-summer3', 'Holiday (summer) internship','Gaining practical knowledge of issues related to the field of study.',8,220,'Summer','Holiday-(summer)-internship-summer3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Semester-internship-summer3', 'Semester internship','Gaining practical knowledge of issues related to the field of study.',5,130,'Summer','Semester-internship-summer3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Diploma-seminar', 'Diploma seminar','The aim of the course is to explain the essence of an engineering diploma thesis, to present the issues proposed in the diploma theses in the field of thesis by students, and also to learn the principles of its editing and conducting literature recognition in the field of thesis',3,40,'Summer','Diploma-seminar.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Eletrical-devices-summer3', 'Electrical devices','Understanding the principles of operation of power equipment, systems and the role of transformer distribution stations, methods of analyzing the reliability of station work. Student is able to design the distribution station system and select the equipment. Planning the experiment, selection of measuring instruments and implementation of the testing system as well as carrying out tests and processing the results.',2,44,'Summer','Eletrical-devices-summer3.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Semester-internship-winter4', 'Semester internship','Gaining practical knowledge of issues related to the field of study.',7,180,'Winter','Semester-internship-winter4.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Diploma-seminar-winter4', 'Diploma seminar','The aim of the course is to learn the principles of analysis and development of own research results, formulate conclusions, create presentations for the pu provide information on the diploma process (documents, dates, diploma exam, scope of exam issues) and prepare students for scientific research in the area of the completed field of study',7,180,'Winter','Diploma-seminar-winter4.pdf','Bsc','control-robotics-and-electrical-engineering'),

('Algebra-with-geometry','Algebra with Geometry','Provide students with basic knowledge of linear algebra in the field of applications in automation and robotics.',5,36,'Winter','Algebra-geometry.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Mathematical-analysis','Mathematical Analysis','Knowledge in differential and integral calculus which is necessary to study engineering sciences. Skills for application of acquired knowledge to theoretical as well as practical problems in other subjects as physics, technical science',6,54,'Winter','Mathematical-analysis.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Ergonomics','Ergonomics','Presenting basic issues concerning ergonomics in modern companies, as well as automation and robotics engineering and in everyday private life. Giving patterns for solving problems concerning the formation of conditions at work with use of, for example, diagnostics and reduction of occupational risk and designing ergonomic solutions. Giving the examples of ergonomic solutions designing: work stands by production machines and by computers. Presenting relations between technique, human well-being, ecology, economy and sociology.',2,10,'Winter','Ergonomics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Introduction-to-programming','Introduction to Programming','The purpose of the education module: 1. Acquainting with the methodology and principles of object oriented programming using the C ++ programming language. 2. Developing students ability to solve problems in the area of modeling and implementation of information systems. Students learn to simulate and analyze the operation of object-oriented IT programs, and plan and document the IT work done. 3. Developing programming skills for students. Creating awareness of the need for a professional approach to technical issues, meticulous familiarization with the documentation of UML-type IT systems. The student learns to set goals and define priorities leading to the implementation of the task through object-oriented implementation of the code.',5,36,'Winter','Introduction-to-programming.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Occupational-Health-and-Safety-university-regulations-protection-of-intellectual-properties','Occupational Health and Safety, university regulations, protection of intellectual properties',' To familiarize students with rules, ordinances and regulations about health and safety at work. To acquaint students with the Basic issues of the methodology of human-oriented design as an operator and as an employee of machine service and other technical devices. Students will be familiarized with major legal regulations from the area of the copyright of the industrial property law and with procedures concerning inventions.',1,10,'Winter','Occupational-Health-and-Safety-university-regulations-protection-of-intellectual-properties.pdf','Bsc','engineering-management'),
('Information-technology','Information Technology','1. Providing students with knowledge of information technologies in the field of their use in automation and robotics. 2. Developing students' skills to solve problems related to the use of information technologies.',3,18,'Winter','Information-technology.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Physics','Physics','1. Providing students with basic knowledge of physics, to the extent specified by the curriculum content appropriate to the field of study 2. Developing students' skills in solving simple problems and performing simple experiments as well as analyzing results based on the knowledge obtained',6,42,'Summer','Physics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Numerical-methods-and-simulation','Numerical Methods and Simulation','Preparing students for using numerical skills in analysis and simulation of systems and processes of analysis in automation and robotics. The course discusses issues related to modeling and description of the phenomenon of growth in automation systems and applications as well as numerical methods of analysis of these systems',4,26,'Summer','Numerical-methods-and-simulation.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Probability-and-statistics','Probability and statistics','Provide students with knowledge of probabilistic methods and the ability to use them to solve practical engineering problems. application of methods and tools of mathematical statistics for data analysis.',4,26,'Summer','Probability-and-statistics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Differential-equations-and-integral-transformations','Differential equations and integral transformations','1. Providing students with basic knowledge of the operator's calculus (Laplace transformation, Z transformation and Fourier transformation basics). 2. To provide students with the basics of using these transformations to solve differential and recursive (differential) equations. 3. To familiarize students with the applications of operator calculus in the study of the dynamics of analog and digital systems. 4. Developing students' teamwork skills.',5,36,'Summer','Differential-equations-and-integral-transformations.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Circuit-theory','Circuit Theory','Course objective is to provide students with basic knowledge about phenomena in electrical systems and laws describing electrical circuits.',7,54,'Summer','Circuit-theory.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Control-basics','Control basics','The lecture aims at presenting to students basic knowledge from control field, concerning especially linear control systems, to prepare them to describe and design tasks. Furthermore, it develops the abilities to describe control systems using formal mathematical language, their stability properties, and performance measures.',7,54,'Winter','Control-basics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Basics-of-electronics','Basics of electronics','1. Providing students with knowledge of basic electronic components, their structure and properties as well as basic analog and digital electronic circuits. 2. Developing students' skills in testing and designing electronic circuits. 3. Developing students' teamwork skills in performing laboratory exercises.',5,42,'Winter','Basics-of-electronics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Structured-and-object-oriented-programming','Structured and object-oriented programming','Purpose of the course: 1. Acquainting with the methodology and principles of structured and object-oriented programming using the C ++ programming language in the scope extended to that presented in semester I and elements of Python. 2. Acquainting with dynamic data structures and their implementation in C ++ and Python. Developing practical skills of adequate use of structures depending on the requirements 3. Ability to implement and adapt standard algorithms to solve a variety of problems, and issues related to computational complexity and optimization 4. Knowledge of basic application design patterns and an example of their use',5,38,'Summer','Structured-and-object-oriented-programming.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Theory-and-Signal-Processing','Theory and Signal Processing','The purpose of the course is to provide students with the basics of knowledge about signal processing techniques and teach how to use this knowledge in practice. 2. Developing students' problem-solving skills related to the selection of appropriate signal processing techniques for specific purposes with the use of computer systems. 3. Teaching the correct application of methods of signal analysis and processing.',8,64,'Winter','Theory-and-signal-processing.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Engineering-Graphics','Engineering Graphics','Transfer of knowledge as well as education and development of skills regarding methods of preparing and reading technical drawings used in the documentation of elements of automation and robotics systems.',4,26,'Summer','Engineering-graphics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Mechanics-and-strength-of-materials','Mechanics and strength of materials','1. Provide students with basic knowledge of statics, kinematics, dynamics and endurance materials. 2. Presentation of construction methods of mathematical models describing real objects. 3. Developing students' skills in solving simple problems in statics, kinematics and dynamics.',4,40,'Summer','Mechanics-and-strength-of-materials.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Fundamentals-of-Robotics','Fundamentals of Robotics','1. Provide students with knowledge of the basics of robotics and in particular knowledge associated with manipulators to their substantive matters of robot dynamics and the synthesis and analysis of robot control systems. 2. Develop students' ability to solve problems related to the mathematical description of the kinematics of the location and differential kinematics of manipulators.',5,38,'Summer','Fundamentals-of-Robotics.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Control-of-continuous-and-discrete-processes','Control of continuous and discrete processes','1. Provide students with knowledge about the mathematical description and operation of discrete linear and selected nonlinear control systems. 2. Developing the ability to solve problems related to the control of discrete and selected nonlinear systems with an emphasis on formulating mathematical models of these systems. 3. Shaping in students the ability to find a mathematical description of a discrete linear control system, the selection of digital regulators, as well as the evaluation of their operation. 4. Developing the ability to formulate a mathematical description of selected continuous nonlinear control systems and their analysis.',7,54,'Summer','Control-of-continuous-and-discrete-processes.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Digital-technology','Digital technology','The student acquires knowledge of the parameters and operation of basic digital systems. He or she acquaintses with methods of designing digital systems and ways of their realization in programmable systems.',4,26,'Summer','Digital-technology.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Devices-of-automation-and-actuators','Devices of automation and actuators','Acquaintance with the basic knowledge of the: construction, principles of operation, and control of the special electrical, electromechanical, pneumatic, and hydraulic converters used in automation systems. Development of students' skills in areas of construction, design, and analysis tasks as well as measurement verification in the laboratory. Creation of the awareness of the need for a professional approach to technical issues, scrupulous reading of the documentation of drives used in automation. Learning the students to set goals and priorities, leading to solving computational tasks and practical implementation of problem solutions.',5,36,'Winter','Devices-of-automation-and-actuators.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Metrology-and-technical-measurement','Metrology and Technical Measurement','Knowledge of the measurement methodology, attributes of the modern measuring equipment, the principles of application of analog and digital devices, and the principles of the evaluation of measurement results.',3,30,'Winter','Metrology-and-technical-measurement.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Modeling-and-control-of-robots','Modeling and control of robots','The aim of the course is: Prodviding students with the basic knowledge necessary to understand the issues of robot control. This includes the transfer of knowledge related to wheeled and handling robots in the scope of modeling their dynamics for control purposes. Developing students' skills in solving problems related to the mathematical description of restrictions imposed on the movement of a mobile robot, manipulation robot control along a given trajectory, taking into account its dynamics model.',5,48,'Winter','Modeling-and-control-of-robots.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Electric-drives','Electric Drives','Getting to know the construction, principles of operation as well as methods and structures of advanced control systems electric drive systems used in heavy industry, industrial robots, electric vehicles, aircrafts, household appliances',5,36,'Winter','Electric-drives.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Programming-of-PLCs-and-industrial-controllers','Programming of PLCs and industrial controllers','1. To provide students with basic knowledge about programming and application of programmable  controllers in control processes, about algorithmization and writing a control program for the whole process (or one task) realized by a programmable controller, about using programming tools for control tasks. 2. To acquire the knowledge and skills to use programmable equipment for the realization of industrial process control, to acquire the ability to use the selected language intended for the programming of the control system, to acquire the ability to operate devices for the realization of digital control and tools used for the programming of industrial systems. 3. Developing students' skills in solving problems in the field of configuration, programming and use of industrial control systems',5,36,'Winter','Programming-of-PLCs-and-industrial-controllers.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Internship','Internship','Gaining practical knowledge of issues related to the field of study.',4,100,'Summer','Internship.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Microprocessor-systems','Microprocessor systems','1. To provide students with basic knowledge about the architecture and programming of microcontrollers. 2. Developing students' skills to solve problems related to data processing and communication using interfaces in microprocessor electronic systems. 3. Developing the importance of knowledge of standards and recommendations related to the construction and programming of microprocessor electronic devices in students.',5,36,'Summer','Microprocessor-systems.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Control-theory','Control theory','1. Provide students with knowledge of control theory, in particular knowledge related to various automation systems, in order to prepare them substantively for issues related to their stability as well as synthesis and analysis of their control. 2. Developing students' skills in solving problems related to the concept of stability in terms of Lyapunov and applying it to a wide class of automation systems. In addition, students will have the ability to construct various observers widely used in technology, optimization of control systems and dynamic programming',6,34,'Summer','Control-theory.pdf','Bsc','control-robotics-and-electrical-engineering'),
('System-identification','System identification ','Extension of student's knowledge on designing and validation of experimental models, build based on measurement data taken from a plant; familiarization of student with selected identification techniques and methods, and shaping skills in implementation and practical utilization of identified models; shaping the skills for cooperation in a small team',4,31,'Winter','System-identification.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Transition-project','Transition project','1. Practical use and consolidation of the student's knowledge in the field of control systems and control and measurement systems as well as the analysis and synthesis of selected control systems on the basis of an independently solved problem in the field of automation and robotics. 2. Developing students' ability to independently solve a given problem related to the issues from the first point. 3. Shaping students' skills to share the obtained conclusions with the group and the ability to transfer the results of research work in an appropriate way.',5,36,'Winter','Transition-project.pdf','Bsc','control-robotics-and-electrical-engineering');
('Real-time-systems','Real Time Systems','The aim goal of the course is to learn the principles of operation and the specifics of real-time systems, real-time operating systems and to learn the methodology for creating real-time applications and to acquire practical skills in creating real-time applications',5,36,'Winter','Real-time-systems.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Preparation-for-scientific-research','Preparation for scientific research','The main aim of the seminar "Preparation for scientific research" is to present the basic methodology of conducting research in the field of Automation and Robotics and to present the subject of research conducted in the units assigned to this field',1,6,'Summer','Preparation-for-scientific-research.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Diploma-thesis-preparation','Diploma Thesis Preparation','The aim of the course is to present students with the principles of preparing a diploma thesis from the substantive and editorial point of view, regulations and principles relevant to the implementation of this type of IT projects, the possibility of further training and developing awareness of the social role of a technical university graduate.',15,10,'Summer','Diploma-thesis-preparation.pdf','Bsc','control-robotics-and-electrical-engineering'),
('Diploma-seminar','Diploma seminar','The aim of the course is to present students with the principles of preparing a diploma thesis from the substantive and editorial point of view, regulations and principles relevant to the implementation of this type of IT projects, the possibility of further training and developing awareness of the social role of avtechnical university graduate.',2,14,'Summer','Diploma-seminar.pdf','Bsc','control-robotics-and-electrical-engineering'),




INSERT INTO coordinator (name, last_name, email) VALUES
('Dariusz','Brzezinski','Dariusz.Brzezinski@cs.put.poznan.pl'),
('Sylwia','Kopczyńska','Sylwia.Kopczynska@cs.put.poznan.pl'),
('Mirosław','Ochodek','Miroslaw.Ochodek@cs.put.poznan.pl'),
('Bartosz','Walter','Bartosz.Walter@put.poznan.pl'),
('Michal','Mackowiak','Michal.Mackowiak@put.poznan.pl'),
('Michal','Tomczyk','Michal.Tomczyk@cs.put.poznan.pl'),
('Maciej','Piernik','Maciej.Piernik@cs.put.poznan.pl'),
('Robert','Susmaga','Robert.Susmaga@cs.put.poznan.pl'),
('Ewa','Hołubowicz','Ewa.Holubowicz@put.poznan.pl');

('Wiesław', 'Grzybowski', wieslaw.grzybowski@put.poznan.pl),
('Adam', 'Buczek', adam.buczek@put.poznan.pl),
('Maciej', 'Berdychowski', maciej.berdychowski@put.poznan.pl),
('Dominik', 'Wilczyński', dominik.wilczynski@put.poznan.pl),
('Wojciech', 'Szeląg', wojciech.szelag@put.poznan.pl)
('Jarosław', 'Gielniak', jaroslaw.gielniak@put.poznan.pl),
('Marian', 'Liskowski', marian.liskowski@put.poznan.pl),
('Leszek', 'Kasprzyk', leszek.kasprzyk@put.poznan.pl),
('Karol', 'Hejne', karol.hejne@put.poznan.pl),
('Arkadiusz', 'Dobrzycki', arkadiusz.dobrzycki@put.poznan.pl),
('Andrzej', 'Graczkowski', andrzej.graczkowski@put.poznan.pl),
('Krystyna', 'Ciesielska', krystyna.ciesielska@put.poznan.pl),
('Andrzej', 'Demenko', Andrzej.Demenko@put.poznan.pl),
('Lech' 'Nowak', Lech.Nowak@put.poznan.pl),
('Barbara', 'Szyszka', barbara.szyszka@put.poznan.pl),
('Arkadiusz', 'Hulewicz', arkadiusz.hulewicz@put.poznan.pl), 
('Przemysław', 'Otomański', przemyslaw.otomanski@put.poznan.pl), 
('Andrzej', 'Tomczewski', andrzej.tomczewski@put.poznan.pl),
('Andrzej', 'Kwapisz', andrzej.kwapisz@put.poznan.pl),
('Joanna', 'Ziętkiewicz', joanna.zietkiewicz@put.poznan.pl), 
('Michał', 'Gwóźdź', Michal.Gwozdz@put.poznan.pl),
('Grażyna', 'Sypniewska-Kamińska', grazyna.sypniewska-kaminska@put.poznan.pl), 
('Krzysztof', 'Wanadchowicz', Wanadchowicz@put.poznan.pl), 
('Małgorzata', 'Zalesińska', Malgorzata.Zalesinska@put.poznan.pl), 
('Wojciech', 'Machczyński', wojciech.machczynski@put.poznan.pl), 
('Justyna', 'Michalak', justyna.michalak@put.poznan.pl), 
('Michał', 'Krystkowiak', Michal.Krystkowiak@put.poznan.pl), 
('Leszek', 'Kasprzyk' , leszek.kasprzyk@put.poznan.pl), 
('Dorota', 'Stachowiak', dorota.stachowiak@put.poznan.pl), 
('Krzysztof', 'Wanadchowicz', Krzysztof.Wanadchowicz@put.poznan.pl), 
('Michał', 'Krystkowiak', Michal.Krystkowiak@put.poznan.pl), 
('Amadeusz', 'Gąsiorek', Amadeusz.Gasiorek@put.poznan.pl), 
('Grzegorz', 'Trzmiel', Grzegorz.Trzmiel@put.poznan.pl),
('Dariusz', 'Prokop', dariusz.prokop@put.poznan.pl),
('Krzysztof', 'Szubert' , Krzysztof.Szubert@put.poznan.pl), 
('Krzysztof', 'Siodła', krzysztof.siodla@put.poznan.pl), 
('Grzegorz', 'Dombek', grzegorz.dombek@put.poznan.pl), 
('Rafał', 'Wojciechowskie', rafal.wojcieiechowski@put.poznan.pl), 
('Andrzej', 'Demenko', andrzej.demenko@put.poznan.pl), 
('Joanna' 'Parzych', joanna.parzych@put.poznan.pl),
 
(Szymon, Drgas, szymon.drgas@put.poznan.pl),
(Damian, Cetnarowicz, damian.cetnarowicz@put.poznan.pl),
(Marian, Liskowski, marian.liskowski@put.poznan.pl),
(Edwin, Tytyk, edwin.tytyk@put.poznan.pl),
(Jakub, Kołota, Jakub.Kolota@put.poznan.pl),
(Rafał, Kapela, Rafal.Kapela@put.poznan.pl),
(Wiesław, Grzybowski, wieslaw.grzybowski@put.poznan.pl),
(Rafał, Kabaciński, rafal.kabacinski@put.poznan.pl),
(Paweł, Szulczyński, Pawel.Szulczynski@put.poznan.pl),
(Jarosław, Ruczkowski, jaroslaw.ruczkowski@put.poznan.pl),
(Janusz, Pochmara, Janusz.Pochmara@put.poznan.pl),
(Sławomir, Stępień, Slawomir.Stepien@put.poznan.pl),
(Ewa, Bakinowska, ewa.bakinowska@put.poznan.pl),
(Janusz, Pochmara, janusz.pochmara@put.poznan.pl),
(Aleksandra, Świtlicka, aleksandra.swietlicka@put.poznan.pl),
(Jakub, Bernat, Jakub.Bernat@put.poznan.pl),
(Stefan, Brock, Stefan.Brock@put.poznan.pl),
(Dariusz, Horla, dariusz.horla@put.poznan.pl),
(Krzysztof, Kozłowski, krzysztof.kozlowski@put.poznan.pl),
(Paweł, Pawłowski, pawel.pawlowski@put.poznan.pl),
(Piotr, Kaczmarek, piotr.kaczmarek@put.poznan.pl),
(Tomasz, Marciniak, tomasz.marciniak@put.poznan.pl),
(Adam, Turkot, adam.turkot@put.poznan.pl),
(Paweł, Drapikowski, pawel.drapikowski@put.poznan.pl),
(Przemysław, Herman,  przemyslaw.herman@put.poznan.pl),
(Jarosław, Warczyński, Jaroslaw.Warczynski@put.poznan.pl),
(Piotr, Dutkiewicz, Piotr.Dutkiewicz@put.poznan.pl),
(Paweł, Szulczyński, pawel.szulczynski@put.poznan.pl),
(Konrad, Urbański,  konrad.urbanski@put.poznan.pl),
(Stanisław, Gardecki,  Stanislaw.Gardecki@put.poznan.pl),
(Sławomir, Stępień,  Slawomir.Stepien@put.poznan.pl),
(Michał, Bołtrukiewicz,  michal.boltrukiewicz@put.poznan.pl),
(Zbigniew, Krawiecki,  zbigniew.krawiecki@put.poznan.pl),
(Piotr, Dutkiewicz,  Piotr.Dutkiewicz@put.poznan.pl),
(Jarosław, Warczyński, Jaroslaw.Warczynski@put.poznan.pl),
(Tomasz, Pajchrowski, tomasz.pajchrowski@put.poznan.pl),
(Jarosław, Majchrzak, jaroslaw.majchrzak@put.poznan.pl),
(Krzysztof, Wandachowicz, Krzysztof.Wandachowicz@put.poznan.pl),
(Tomasz, Marciniak, Tomasz.Marciniak@put.poznan.pl),
(Dominik, Łuczak, Dominik.Luczak@put.poznan.pl),
(Krzysztof, Kozłowski, krzysztof.kozlowski@put.poznan.pl),
(Andrzej, Kasiński, andrzej.kasinski@put.poznan.pl),
(Joanna, Ziętkiewicz, joanna.zietkiewicz@put.poznan.pl),
(Maciej, Marcin Michałek, maciej.michalek@put.poznan.pl),
(Piotr, Dutkiewicz, Piotr.Dutkiewicz@put.poznan.pl),
(Dariusz, Pazderski, dariusz.pazderski@put.poznan.pl), 
(Jarosław, Warczyński, jaroslaw.warczynski@put.poznan.pl),
(Janusz, Pochmara, janusz.pochmara@put.poznan.pl),
(Krzysztof, Kozłowski, krzysztof.kozlowski@put.poznan.pl),
(Andrzej, Kasiński, andrzej.kasinski@put.poznan.pl),
(Krzysztof, Kozłowski, krzysztof.kozlowski@put.poznan.pl),
(Andrzej, Kasiński, andrzej.kasinski@put.poznan.pl),
(Krzysztof, Kozłowski, krzysztof.kozlowski@put.poznan.pl),
(Andrzej, Kasiński, andrzej.kasinski@put.poznan.pl),

INSERT INTO course_coordinators (course_id, coordinators_email) VALUES
('object-programming','Dariusz.Brzezinski@cs.put.poznan.pl'),
('quality-management-experimental-software-engineering','Sylwia.Kopczynska@cs.put.poznan.pl'),
('quality-management-experimental-software-engineering','Miroslaw.Ochodek@cs.put.poznan.pl'),
('software-architecture-and-verification','Bartosz.Walter@put.poznan.pl'),
('software-architecture-and-verification','Michal.Mackowiak@put.poznan.pl'),
('software-development-studio-2','Sylwia.Kopczynska@cs.put.poznan.pl'),
('software-development-studio-2','Miroslaw.Ochodek@cs.put.poznan.pl'),
('operational-research','Michal.Tomczyk@cs.put.poznan.pl'),
('internet-applications','Maciej.Piernik@cs.put.poznan.pl'),
('information-theory','Robert.Susmaga@cs.put.poznan.pl'),
('career-resources','Ewa.Holubowicz@put.poznan.pl');
('Occupational-health-and-safety', 'wieslaw.grzybowski@put.poznan.pl'),
('Physics','adam.buczek@put.poznan.pl'),
('Geometry-and-engineering-graphics', 'maciej.berdychowski@put.poznan.pl'),
('Geometry-and-engineering-graphics', 'dominik.wilczynski@put.poznan.pl'),
('Information-Engineering', 'wojciech.szelag@put.poznan.pl'),
('Materials-engineering', 'jaroslaw.gielniak@put.poznan.pl'),
('Mathematics', 'marian.liskowski@put.poznan.pl'),
('Circuits-theory', 'leszek.kasprzyk@put.poznan.pl'),
('Physical-education', 'karol.hejne@put.poznan.pl'),
('Physics', 'adam.buczek@put.poznan.pl')
('Information-technology', 'arkadiusz.dobrzycki@put.poznan.pl'),
('Materials-engineering-Summer', 'andrzej.graczkowski@put.poznan.pl'),
('English', 'krystyna.ciesielska@put.poznan.pl'
('Electrical-machines', 'Andrzej.Demenko@put.poznan.pl'),
('Electrical-machines', 'Lech.Nowak@put.poznan.pl'),
('Mathematics-Summer', 'marian.liskowski@put.poznan.pl'),
('Numerical-methods', 'barbara.szyszka@put.poznan.pl'),
('Metrology', 'arkadiusz.hulewicz@put.poznan.pl'), 
('Metrology', 'przemyslaw.otomanski@put.poznan.pl'),
('Circuits-theory-Summer', 'andrzej.tomczewski@put.poznan.pl'),
('Physical-education-Summer', 'karol.hejne@put.poznan.pl'),
('Automation-and-automatic-regulation', 'andrzej.kwapisz@put.poznan.pl'), 
('Automation-and-automatic-regulation', 'joanna.zietkiewicz@put.poznan.pl'),
('Electronics-and-power-electronics', 'Michal.Gwozdz@put.poznan.pl'),
('Information-technology-winter2', 'Michal.Gwozdz@put.poznan.pl'),
('English-winter2', 'krystyna.ciesielska@put.poznan.pl'),
('Electrical-machines-winter2', 'Andrzej.Demenko@put.poznan.pl'),
('Electrical-machines-winter2', 'Lech.Nowak@put.poznan.pl'),
('Mechanics-and-mechatronics', 'grazyna.sypniewska-kaminska@put.poznan.pl'),
('Metrology-winter2', 'arkadiusz.hulewicz@put.poznan.pl'), 
('Metrology-winter2', 'przemyslaw.otomanski@put.poznan.pl'), 
('Basics-of-Lighting-Engineering', 'Wanadchowicz@put.poznan.pl'),
('Basics-of-Lighting-Engineering', 'Malgorzata.Zalesinska@put.poznan.pl'),
('Electromagnetic-Field-Theory', 'wojciech.machczynski@put.poznan.pl'),
('Electrical-Power-Engineering', 'justyna.michalak@put.poznan.pl'),
('Electronics-and-power-electronics-summer2', 'Michal.Krystkowiak@put.poznan.pl'), 
('English-summer2', 'krystyna.ciesielska@put.poznan.pl'), 
('Computerization-of-design-in-electrical-engineering', 'leszek.kasprzyk@put.poznan.pl'),
('Electrical-machines-summer2', 'Andrzej.Demenko@put.poznan.pl'), 
('Electrical-machines-summer2', Lech.Nowak@put.poznan.pl),
('Mechanics-and-mechatronics-summer2', 'dorota.stachowiak@put.poznan.pl'),
('Holiday-(summer)-internship', 'Krzysztof.Wanadchowicz@put.poznan.pl'),
('High-voltage-engineering', 'Krzysztof.Wanadchowicz@put.poznan.pl', 'Krzysztof.Wanadchowicz@put.poznan.pl'),
('Electrical-Power-Engineering-winter3', 'justyna.michalak@put.poznan.pl'), 
('Electronics-and-power-electronics-winter3', 'Michal.Krystkowiak@put.poznan.pl'), 
('Electronics-and-power-electronics-winter3','Amadeusz.Gasiorek@put.poznan.pl'),
('Computerization-of-design-in-electrical-engineering-winter3', 'leszek.kasprzyk@put.poznan.pl'),
('Renewable-energy-sources', 'Grzegorz.Trzmiel@put.poznan.pl'),
('Optoelectronic', 'dariusz.prokop@put.poznan.pl'),
('Semester-internship', 'Krzysztof.Wanadchowicz@put.poznan.pl'),
('Transmission-and-distribution-of-electric-power-energy', 'Krzysztof.Szubert@put.poznan.pl'),
('Microprocessor-technology', 'Grzegorz.Trzmiel@put.poznan.pl'),
('High-voltage-engineering-winter3', 'krzysztof.siodla@put.poznan.pl'),
('Electrical-devices', 'grzegorz.dombek@put.poznan.pl'),
('Introduction-to-telecommunication', 'andrzej.tomczewski@put.poznan.pl'),
('Technical-Electrodynamics', 'rafal.wojcieiechowski@put.poznan.pl'),
('Technical-Electrodynamics', 'andrzej.demenko@put.poznan.pl'),
('Ergonomics-and-safety-use-of-electrical-equipment', 'grzegorz.dombek@put.poznan.pl'),
('Optoelectronic-summer3', 'joanna.parzych@put.poznan.pl'),
('Holiday-(summer)-internship-summer3', 'Krzysztof.Wanadchowicz@put.poznan.pl'),
('Semester-internship-summer3', 'Krzysztof.Wanadchowicz@put.poznan.pl'),
('Diploma-seminar', ''),
('Eletrical-devices-summer3', 'Krzysztof.Wanadchowicz@put.poznan.pl'), 
('Semester-internship-winter4', 'Krzysztof.Wanadchowicz@put.poznan.pl'),
('Diploma-seminar-winter4', ''), 

 ('Algebra-with-geometry', 'damian.cetnarowicz@put.poznan.pl'), 
('Algebra-with-geometry', 'szymon.drgas@put.poznan.pl'),
('Mathematical-analysis','marian.liskowski@put.poznan.pl'),
('Ergonomics', 'edwin.tytyk@put.poznan.pl'),
('Introduction-to-programming', 'Rafal.Kapela@put.poznan.pl'),
('Introduction-to-programming', 'Jakub.Kolota@put.poznan.pl'),
('Occupational-Health-and-Safety-university-regulations-protection-of-intellectual-properties', 'wieslaw.grzybowski@put.poznan.pl'),
('Information-technology', 'Pawel.Szulczynski@put.poznan.pl'), 
('Information-technology', 'rafal.kabacinski@put.poznan.pl'),
('Physics', 'jaroslaw.ruczkowski@put.poznan.pl'),
('Numerical-methods-and-simulation', 'Slawomir.Stepien@put.poznan.pl'), 
('Numerical-methods-and-simulation', 'Janusz.Pochmara@put.poznan.pl'),
('Probability-and-statistics', 'ewa.bakinowska@put.poznan.pl'),
('Differential-equations-and-integral-transformations', 'aleksandra.swietlicka@put.poznan.pl'), 
('Differential-equations-and-integral-transformations', 'janusz.pochmara@put.poznan.pl'),
('Circuit-theory', 'Stefan.Brock@put.poznan.pl'), 
('Circuit-theory', 'Jakub.Bernat@put.poznan.pl'),
('Control-basics', 'krzysztof.kozlowski@put.poznan.pl'),
('Control-basics', 'dariusz.horla@put.poznan.pl'),
('Basics-of-electronics', 'pawel.pawlowski@put.poznan.pl'
('Structured-and-object-oriented-programming', 'piotr.kaczmarek@put.poznan.pl'),
('Theory-and-Signal-Processing', 'tomasz.marciniak@put.poznan.pl'),
('Engineering-Graphics', 'pawel.drapikowski@put.poznan.pl'), 
('Engineering-Graphics', 'adam.turkot@put.poznan.pl'),
('Mechanics-and-strength-of-materials', 'przemyslaw.herman@put.poznan.pl'),
('Fundamentals-of-Robotics', 'Piotr.Dutkiewicz@put.poznan.pl'), 
('Fundamentals-of-Robotics', 'Jaroslaw.Warczynski@put.poznan.pl'), 
('Control-of-continuous-and-discrete-processes', 'pawel.szulczynski@put.poznan.pl'),
('Digital-technology', 'konrad.urbanski@put.poznan.pl'),
('Devices-of-automation-and-actuators', 'Stanislaw.Gardecki@put.poznan.pl'),
('Devices-of-automation-and-actuators', 'Slawomir.Stepien@put.poznan.pl'),
('Metrology-and-technical-measurement', 'zbigniew.krawiecki@put.poznan.pl'), 
('Metrology-and-technical-measurement', 'michal.boltrukiewicz@put.poznan.pl'), 
('Modeling-and-control-of-robots', 'Piotr.Dutkiewicz@put.poznan.pl'),
('Modeling-and-control-of-robots', Jaroslaw.Warczynski@put.poznan.pl'),
('Electric-drives', 'tomasz.pajchrowski@put.poznan.pl'),
('Programming-of-PLCs-and-industrial-controllers', 'jaroslaw.majchrzak@put.poznan.pl'),
('Internship', 'Krzysztof.Wandachowicz@put.poznan.pl'),
('Microprocessor-systems', 'Dominik.Luczak@put.poznan.pl'),
('Microprocessor-systems', 'Tomasz.Marciniak@put.poznan.pl'),
('Control-theory', 'krzysztof.kozlowski@put.poznan.pl'), 
('Control-theory', 'andrzej.kasinski@put.poznan.pl'),
('System-identification', 'joanna.zietkiewicz@put.poznan.pl'), 
('System-identification', 'maciej.michalek@put.poznan.pl'),
('Transition-project', 'dariusz.pazderski@put.poznan.pl'), 
('Transition-project', 'Piotr.Dutkiewicz@put.poznan.pl'), 
('Real-time-systems', 'jaroslaw.warczynski@put.poznan.pl'), 
('Real-time-systems', 'janusz.pochmara@put.poznan.pl'), 
('Preparation-for-scientific-research', 'krzysztof.kozlowski@put.poznan.pl'), 
('Preparation-for-scientific-research', 'andrzej.kasinski@put.poznan.pl'),
('Diploma-thesis-preparation', 'krzysztof.kozlowski@put.poznan.pl'), 
('Diploma-thesis-preparation', 'andrzej.kasinski@put.poznan.pl'),
('Diploma-seminar','Diploma seminar', 'Krzysztof.Wandachowicz@put.poznan.pl'),


INSERT INTO erasmus_student (lastname, firstname, email, password) VALUES
('COAT', 'Arthur', 'arthur.coat@student.put.poznan.pl', '$2a$10$TCdrvG6zWUwrryQ.7Id6Qe9lJCWXaykTFH1vfRyrSRkmF5KK0DoCa');

INSERT INTO testimonial (id, erasmus_student_email, date, comment, course_id) VALUES
(1, 'arthur.coat@student.put.poznan.pl', '2022-01-06 18:07:32', 'This is a comment', 'quality-management-experimental-software-engineering');
